### ISSUE TITLE
Library is invalid due to missing author and maintainer in library.properties

### ISSUE THREAD

**Issue by per1234** [u-fire/ECSalinity#1]
Due to the missing `author` and `maintainer` fields in library.,properties the library can't be installed via **Sketch > Include Library > Add .ZIP library...**, the example sketch doesn't appear under **File > Examples**, and compiling any sketch that includes the library fails. This occurs with any recent version of the Arduino IDE, probably 1.6.6 and newer (excluding the 1.7.x arduino.org versions).

More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by u-fire** [comment]
Fixed in release v1.0.1.
