### ISSUE TITLE
Compatibility with Arduino MKR Wifi 1010

### ISSUE THREAD

**Issue by nano2K** [u-fire/ECSalinity#8]
This library does not seem to be compatible with SAMD21-based microcontrollers like the MKR Wifi 1010. Compiling and uploading any of the example sketches (or simply trying to instantiate `EC_Salinity ec;`) leads to the device to become unresponsive for serial connections (no COM port connection is possible anymore afterwards and the device needs to be reset using the hardware button)

Do you have any idea what could be the reason for this behaviour?

**Comment by justind000** [comment]
This was pointed out with the other board's library as well a few days ago (https://github.com/u-fire/ISE_Probe/issues/3). I don't have a SAMD based board yet, so there's not much I can do at the moment. My guess is it has something to do with the headers or Wire implementation. I'm waiting on one in the mail, but if you get it figured out, I'd appreciate the information or PR.

**Comment by nano2K** [comment]
Just a quick heads up: It looks like a bug in either the Wire library or the implementation of it. I am currently trying to isolate the issue further, but that's mostly trial and error without a dedicated debugger :-)

**Comment by justind000** [comment]
So I got an Adafruit Feather M0 to try this with and got it working without any change to the library, although there will need to be a change in the future. 

The TLDR version is you just need to use arrow notation to access the class members. 

```
#include <ECSalinity.h>

EC_Salinity *ec;

void setup() {
  ec = new EC_Salinity(0x3c);
  Serial.begin(9600);

  while (!Serial);
  Serial.println(ec->getVersion(), HEX);
}

void loop() {}
```
I don't know enough about the M0 to guess why it doesn't like the Wire library initialization in the class initialization. My first thoughts on a good permanent fix for this are to include a ::begin() method like most Arduino-type libraries have. I just wanted to let you know how to get some use out of it as-is for now though.

**Comment by nano2K** [comment]
It's working for now. Thank you.
